import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#060B08",
        "surface-container-low": "#0E1712",
        "surface-container": "#132019",
        "surface-container-high": "#1C2E24",
        "surface-container-highest": "#263D30",
        surface: "#060B08",
        background: "#060B08",
        "on-surface": "#FFFFFF",
        "on-background": "#FFFFFF",
        lime: {
          DEFAULT: "#84CC16",
          50: "#F7FEE7",
          100: "#ECFCCB",
          200: "#D9F99D",
          300: "#BEF264",
          400: "#A3E635",
          500: "#84CC16",
          600: "#65A30D",
          700: "#4D7C0F",
          800: "#3F6212",
          900: "#365314",
        },
        cyan: {
          DEFAULT: "#84CC16",
          50: "#F7FEE7",
          100: "#ECFCCB",
          200: "#D9F99D",
          300: "#BEF264",
          400: "#A3E635",
          500: "#84CC16",
          600: "#65A30D",
          700: "#4D7C0F",
          800: "#3F6212",
          900: "#365314",
        },
        violet: {
          DEFAULT: "#10B981",
          50: "#ECFDF5",
          100: "#D1FAE5",
          200: "#A7F3D0",
          300: "#6EE7B7",
          400: "#34D399",
          500: "#10B981",
          600: "#059669",
          700: "#047857",
          800: "#065F46",
          900: "#064E3B",
        },
        twin: {
          bg: "#060B08",
          panel: "#0E1712",
          border: "#1C2E24",
          cyan: "#84CC16",
          violet: "#10B981",
          good: "#A3E635",
          warn: "#FBBF24",
          bad: "#F87171",
          text: "#FFFFFF",
          muted: "#A3B899",
        },
      },
      fontFamily: {
        sans: ["Comfortaa", "cursive", "sans-serif"],
        display: ["Comfortaa", "cursive", "sans-serif"],
        comfortaa: ["Comfortaa", "cursive", "sans-serif"],
        inter: ["Comfortaa", "cursive", "sans-serif"],
        grotesk: ["Comfortaa", "cursive", "sans-serif"],
        "label-md": ["Comfortaa", "sans-serif"],
        "body-md": ["Comfortaa", "sans-serif"],
        "headline-lg": ["Comfortaa", "sans-serif"],
        "headline-md": ["Comfortaa", "sans-serif"],
        "body-lg": ["Comfortaa", "sans-serif"],
        "display-lg": ["Comfortaa", "sans-serif"],
        "metric-xl": ["Comfortaa", "sans-serif"],
        "label-sm": ["Comfortaa", "sans-serif"],
        "headline-lg-mobile": ["Comfortaa", "sans-serif"],
        "display-xl": ["Comfortaa", "sans-serif"],
      },
      spacing: {
        gutter: "16px",
        xl: "32px",
        xxl: "64px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        margin: "24px",
        base: "8px",
        "container-max": "1280px",
      },
      keyframes: {
        "breathe-pulse": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.8" },
          "50%": { transform: "scale(1.05)", opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "breathe-pulse": "breathe-pulse 6s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.5s ease-out forwards",
        "slide-in-left": "slide-in-left 0.4s ease-out forwards",
      },
    },
  },
  plugins: [],
};

export default config;
